import { IUser } from '@/types/users'

interface DB {
  users: IUser[]
}

export const db: DB = {
  users: [
    {
      id: 1,
      fullName: "محسن صادقی",
      role: [1],
      contact: "091232611547",
      email: "gslixby0@abc.net.au",
      avatar: "avatar1",
      createDate: "1403/02/02",
      isActive: true,
      expireDate: "1403/10/01",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 2,
      fullName: "علی محمدی",
      role: [1],
      contact: "09121234567",
      email: "alimohammadi@abc.net.au",
      avatar: "avatar2",
      createDate: "1403/02/03",
      isActive: true,
      expireDate: "1403/10/02",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 3,
      fullName: "سارا احمدی",
      role: [2],
      contact: "09129876543",
      email: "sarahmad1390@abc.net.au",
      avatar: "avatar3",
      createDate: "1403/02/04",
      isActive: false,
      expireDate: "1403/08/01",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 4,
      fullName: "مریم کریمی",
      role: [3],
      contact: "09134561234",
      email: "maryam.karimi@abc.net.au",
      avatar: "avatar4",
      createDate: "1403/02/05",
      isActive: true,
      expireDate: "1403/10/15",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 5,
      fullName: "حمیدرضا نیکخواه",
      role: [2],
      contact: "09151234567",
      email: "hamidrezanik@abc.net.au",
      avatar: "avatar5",
      createDate: "1403/02/06",
      isActive: true,
      expireDate: "1403/09/20",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 6,
      fullName: "نیما رضایی",
      role: [3],
      contact: "09161234567",
      email: "nimarezaei@abc.net.au",
      avatar: "avatar6",
      createDate: "1403/02/07",
      isActive: false,
      expireDate: "1403/07/10",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 7,
      fullName: "فرامرز حسینی",
      role: [1],
      contact: "09171234567",
      email: "faramarz.hosseini@abc.net.au",
      avatar: "avatar7",
      createDate: "1403/02/08",
      isActive: true,
      expireDate: "1403/10/25",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 8,
      fullName: "آرزو زاده",
      role: [2],
      contact: "09181234567",
      email: "arezoo.zadeh@abc.net.au",
      avatar: "avatar8",
      createDate: "1403/02/09",
      isActive: true,
      expireDate: "1403/12/05",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 9,
      fullName: "نیلوفر توکلی",
      role: [3],
      contact: "09191234567",
      email: "niloofer.tavakoli@abc.net.au",
      avatar: "avatar9",
      createDate: "1403/02/10",
      isActive: false,
      expireDate: "1403/06/30",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 10,
      fullName: "کوروش بزرگ",
      role: [2],
      contact: "09091234567",
      email: "kourosh.bazargani@abc.net.au",
      avatar: "avatar10",
      createDate: "1403/02/11",
      isActive: true,
      expireDate: "1403/10/30",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 11,
      fullName: "لادن صادقی",
      role: [3],
      contact: "09112345678",
      email: "ladan.sadighi@abc.net.au",
      avatar: "avatar11",
      createDate: "1403/02/12",
      isActive: true,
      expireDate: "1403/09/15",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 12,
      fullName: "پویش نیکفر",
      role: [1],
      contact: "09122345678",
      email: "pooyesh.nikfar@abc.net.au",
      avatar: "avatar12",
      createDate: "1403/02/13",
      isActive: true,
      expireDate: "1403/10/01",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 13,
      fullName: "سید امیر حسین زاده",
      role: [2],
      contact: "09132345678",
      email: "sayed.amir@abc.net.au",
      avatar: "avatar13",
      createDate: "1403/02/14",
      isActive: false,
      expireDate: "1403/07/20",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 14,
      fullName: "مهدی یهکری",
      role: [3],
      contact: "09142345678",
      email: "mahdi.yekahri@abc.net.au",
      avatar: "avatar14",
      createDate: "1403/02/15",
      isActive: true,
      expireDate: "1403/09/30",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 15,
      fullName: "صمد رحیمی",
      role: [1],
      contact: "09152345678",
      email: "samad.rahimi@abc.net.au",
      avatar: "avatar15",
      createDate: "1403/02/16",
      isActive: true,
      expireDate: "1403/10/20",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 16,
      fullName: "فاطمه عبداللهی",
      role: [2],
      contact: "09162345678",
      email: "fatemeh.abdollahi@abc.net.au",
      avatar: "avatar16",
      createDate: "1403/02/17",
      isActive: false,
      expireDate: "1403/08/05",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 17,
      fullName: "علی نجاتی",
      role: [3],
      contact: "09172345678",
      email: "ali.nejati@abc.net.au",
      avatar: "avatar17",
      createDate: "1403/02/18",
      isActive: true,
      expireDate: "1403/11/01",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 18,
      fullName: "بهاره رضایی",
      role: [2],
      contact: "09182345678",
      email: "bahareh.rezaei@abc.net.au",
      avatar: "avatar18",
      createDate: "1403/02/19",
      isActive: true,
      expireDate: "1403/10/15",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 19,
      fullName: "سعید یوسفی",
      role: [3],
      contact: "09192345678",
      email: "sayed.yousefi@abc.net.au",
      avatar: "avatar19",
      createDate: "1403/02/20",
      isActive: false,
      expireDate: "1403/06/28",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    },
    {
      id: 20,
      fullName: "شهرزاد نوری",
      role: [1],
      contact: "09012345678",
      email: "shahrzad.noori@abc.net.au",
      avatar: "avatar20",
      createDate: "1403/02/21",
      isActive: true,
      expireDate: "1403/10/10",
      description: "این کاربر به صورت تستی ایجاد شده است",
      isSelected: false,
      isLoading: false,
      selectable: false,
      disabled: false
    }
  ],
}
